// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/level1","id":"2"},"3":{"path":"/level2","id":"3"},"4":{"path":"/level3","id":"4"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__level1__index" */'@/pages/level1/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__level2__index" */'@/pages/level2/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__level3__index" */'@/pages/level3/index.tsx')),
},
  };
}
